{% set name = "hextools" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hextools-{{ version }}.tar.gz
  sha256: 5c2cddae7bcc17b316980647843d25aa5c79aaa5f626f1fe01ed9ed526814fa0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools >=61
    - setuptools-scm >=7
  run:
    - python >=3.8
    - area-detector-handlers
    - caproto
    - event-model >=1.21.0
    - h5py
    - numpy
    - ophyd
    - pillow
    - pyepics
    - tifffile

test:
  imports:
    - hextools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/NSLS-II-HEX/hextools
  summary: Tools for NSLS-II HEX beamline
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/NSLS-II-HEX/hextools

extra:
  recipe-maintainers:
    - mrakitin
