{% set name = "hextools" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hextools-{{ version }}.tar.gz
  sha256: 5b4cc0cfcf7da42be2112b37426dc4c127784fc80ed7c14853ca7c0e13eca83c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61
    - setuptools-scm >=7
    - pip
  run:
    - python >={{ python_min }}
    - area-detector-handlers
    - caproto
    - event-model >=1.21.0
    - h5py
    - numpy
    - ophyd
    - pillow
    - pyepics
    - tifffile

test:
  imports:
    - hextools
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/NSLS-II-HEX/hextools
  summary: Tools for NSLS-II HEX beamline
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/NSLS-II-HEX/hextools

extra:
  recipe-maintainers:
    - mrakitin
